#ifndef INPUT_EVENTS_H
#define INPUT_EVENTS_H

// Defines the possible input events from the user.
enum class InputEvent {
    INPUT_EVENT_NONE,
    
    INPUT_EVENT_UP,
    INPUT_EVENT_UP_LONG_PRESS,
    INPUT_EVENT_UP_REPEAT,

    INPUT_EVENT_DOWN,
    INPUT_EVENT_DOWN_LONG_PRESS,
    INPUT_EVENT_DOWN_REPEAT,

    INPUT_EVENT_LEFT,
    INPUT_EVENT_LEFT_LONG_PRESS,
    INPUT_EVENT_LEFT_REPEAT,

    INPUT_EVENT_RIGHT,
    INPUT_EVENT_RIGHT_LONG_PRESS,
    INPUT_EVENT_RIGHT_REPEAT,

    INPUT_EVENT_ENTER,
    INPUT_EVENT_ENTER_LONG_PRESS,
    INPUT_EVENT_ENTER_REPEAT
};

#endif // INPUT_EVENTS_H
